### ------------------------------------------------------------------------
### Test requests for the /browse API.
### ------------------------------------------------------------------------

@server = http://localhost:4004
@me = Authorization: Basic {{$processEnv USER}}:

### ------------------------------------------------------------------------
# Get /browse service info
GET {{server}}/browse
{{me}}

### ------------------------------------------------------------------------
# Get /browse service metadata
GET {{server}}/browse/$metadata
{{me}}

### ------------------------------------------------------------------------
# Browse Books as any user
GET {{server}}/browse/ListOfBooks?
  &$select=title,stock
  &$expand=genre
  &sap-language=de
{{me}}

### ------------------------------------------------------------------------
# Browse Genres sa any user
GET {{server}}/browse/Genres?
&$select=name
&$filter=parent_ID eq null
&$expand=children($select=name)
{{me}}

### ------------------------------------------------------------------------
# Submit Order as anonymous user
POST {{server}}/browse/submitOrder
Content-Type: application/json

{ "book":201, "quantity":5 }

### ------------------------------------------------------------------------
# Submit Order as authenticated user
# (send that three times to get out-of-stock message)
POST {{server}}/browse/submitOrder
Content-Type: application/json
{{me}}

{ "book":201, "quantity":5 }